### ISSUE TITLE
gazebo for arm64 architecture

### ISSUE THREAD

**Issue by ARLunan** [canonical/ignition_snap#11]
Is this soon to be available - necessary for Ubuntu 22.04 Virtual Machine on MAC MI Apple Silicon?

**Comment by Guillaumebeuzeboc** [comment]
Thank you for opening this issue.
From the official [Gazebo Citadel support issue](https://github.com/gazebo-tooling/release-tools/issues/595), the arm64 architecture doesn't seem to be part of the CI. Thus, the building status is probably just "best-effort".
I currently do not have any arm64 device that I could use to test the snap build and eventually try to run the snap on an arm64 system.

By any chance, did you try to build the snap locally on your machine?

**Comment by ARLunan** [comment]
Tried sudo snap install gazebo --channel=citadel/beta on 3 machines: 1) Ub22.04 Partition on a Dell x84-64amd64 - result is successful Install  2) UB22.04 VM machine aarch64 on MAC M1 (Apple Silicon)  and 3) Ub20.04 both - snap version 2.58 - error: snap "gazebo" is not available on this architecture (arm64) but exists
       on other architectures (amd64).

**Comment by Guillaumebeuzeboc** [comment]
Indeed, so far, the CI is only building for the amd64 architecture. The snapstore is not yet distributing an arm64 of Gazebo, which is why you are getting this error.
If you still have an aarch64 VM available, you could try to build it locally by following the next steps.
```
sudo snap install snapcraft --classic
git clone https://github.com/canonical/gazebo_snap.git
cd gazebo_snap
sed -i 's|amd64|amd64\, arm64|g' snap/snapcraft.yaml
SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS=1 snapcraft
```
This should build the snap, and then you can install it with:
```
sudo snap install gazebo_citadel*.snap
```

The Gazebo snap relies on an extension that was recently enabled on arm64 architecture, that is why we didn't try it. I would be very curious of your feedback if you were to try it.

**Comment by ARLunan** [comment]
I realized my objective was  to install gazebo sim garden,  not "gazebo classic" or, recently named ignition gazebo) which was to follow the Binary Installation on Ubuntus procedure here: https://gazebosim.org/docs/garden/install: Garden binaries are provided for Ubuntu Focal and Jammy. The Garden binaries are hosted in the packages.osrfoundation.org repository. To install all of them, the metapackage gz-garden can be installed.
